### ISSUE TITLE
Hardcoded binary path

### ISSUE THREAD

**Issue by kek91** [philippeowagner/openingithub#1]
The path for Github App is hardcoded in your python file (`GITHUB_BINARY = "/usr/local/bin/github"`). Would be better if you made a config file in the data directory\Plugins\User\ directory so updates won't break the plugin for users.

fman API suggests naming convention for config file here: [https://fman.io/docs/plugins-caveats](https://fman.io/docs/plugins-caveats)

**Comment by philippeowagner** [comment]
Sure, this could be done better. Would be happy @kek91 to merge your pull request.

**Comment by kek91** [comment]
Great! I might not be able to make it tonight, but I'll submit it tomorrow if that's ok.
